# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efd6da66091aab813fd3391cd46f8f7fe8ccec217f6e1f9f3a4f5a9c208825b9fdbd0da1d4076d580c1f5c74fabaf00632c13ba5d26aba2fcd5504938692ea26

test:
  secret_key_base: dceb8add1c0d8fb4ef76fa1278d0d18c970a7af26f17ebb31f5cab051df19caa2d88d1fad5964f6208f4332667093ba1feb25d9a299bd3015a105c2d7104b96c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
